"use client";
import {useEffect,useState,useRef,type FormEvent} from "react";
import HumanCheck,{type HumanCheckHandle} from "./HumanCheck";
import {useAccount} from "./AccountProvider";
import "./accounts.css";
export default function AccountPanel(){
 const humanCheck=useRef<HumanCheckHandle>(null);
 const {user,loading,error,refresh}=useAccount();const [mode,setMode]=useState<'login'|'signup'>('login'),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[pending,setPending]=useState(false),[message,setMessage]=useState('');
 useEffect(()=>{const result=new URLSearchParams(window.location.search).get('account');if(result==='confirmed')setMessage('Email confirmed. Your account is ready.');if(result==='confirmation-failed')setMessage('This confirmation link expired or was opened in another browser. Try signing in if your email is already confirmed, or create the account again to request a new link.');},[]);
 async function submit(e?:FormEvent){e?.preventDefault();if(pending)return;setPending(true);setMessage('');try{const turnstileToken=user?undefined:await humanCheck.current?.verify();if(!user&&!turnstileToken)throw Error('Human verification is unavailable.');const r=await fetch('/api/account',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(user?{action:'logout'}:{action:mode,email,password,turnstileToken})});const b=await r.json();if(!r.ok)throw Error(b.error?.message??'Could not complete account action.');setPassword('');setMessage(user?'Signed out.':b.message);await refresh();}catch(e){setMessage(e instanceof Error?e.message:'Connection failed.');}finally{setPending(false);}}
 return <section id="account" className="df-section df-account" aria-labelledby="account-title"><div><p className="df-eyebrow">YOUR OWN CREATIVE SPACE</p><h2 id="account-title">{user?'Welcome back.':'Keep what you create.'}</h2><p>{user?user.email:'Sign in to generate images and keep a private history.'}</p></div><div className="df-account-controls">
 {loading?<p role="status">Checking your account…</p>:user?<><a href="#history" className="df-pill df-ink">Your private gallery ↓</a><button disabled={pending} onClick={()=>void submit()}>Sign out</button></>:<form onSubmit={submit}><div className="df-account-tabs"><button type="button" aria-pressed={mode==='login'} onClick={()=>setMode('login')}>Sign in</button><button type="button" aria-pressed={mode==='signup'} onClick={()=>setMode('signup')}>Create account</button></div><label>Email<input type="email" autoComplete="email" required maxLength={254} value={email} onChange={e=>setEmail(e.target.value)} disabled={pending}/></label><label>Password<input type="password" autoComplete={mode==='signup'?'new-password':'current-password'} minLength={mode==='signup'?12:1} maxLength={128} required value={password} onChange={e=>setPassword(e.target.value)} disabled={pending}/></label>{mode==='signup'&&<p className="df-note">Use at least 12 characters. Confirm your email in this browser.</p>}<button className="df-generate" disabled={pending}>{pending?'Please wait…':mode==='login'?'Sign in':'Create account'}</button></form>}
 {!user&&<HumanCheck ref={humanCheck} action="account"/>}{error&&<p role="alert" className="df-error">{error} <button onClick={()=>void refresh()}>Retry</button></p>}<p role="status" className="df-note">{message}</p></div></section>;
}
