"use client";
import {useEffect,useRef,useState,type FormEvent} from 'react';
import {type GenerationStyle} from '../../config/generation';
import HumanCheck,{type HumanCheckHandle} from './HumanCheck';
import './fireball-guide.css';
export type GuideRequest={prompt:string;style:GenerationStyle;count:number};
export type GuideOutcome={completed:number;error?:string;cancelled?:boolean};
type Props={currentPrompt:string;signedIn:boolean;busy:boolean;progress:number;onApply:(prompt:string,options?:{style:GenerationStyle;count:number})=>void;onGenerate:(request:GuideRequest)=>Promise<GuideOutcome>;onStop:()=>void};
type Step='idea'|'enhancing'|'review'|'count'|'style'|'countdown'|'generating'|'done';
const styles:{name:GenerationStyle;detail:string}[]=[{name:'Cinematic',detail:'Light, atmosphere, drama'},{name:'Illustration',detail:'Expressive drawn artwork'},{name:'Dreamscape',detail:'Surreal and imaginative'},{name:'3D art',detail:'Sculpted forms and depth'}];
export default function FireballGuide(props:Props){
 const [mounted,setMounted]=useState(false),[open,setOpen]=useState(false),[step,setStep]=useState<Step>('idea');
 const [idea,setIdea]=useState(''),[draft,setDraft]=useState(''),[count,setCount]=useState(1),[style,setStyle]=useState<GenerationStyle>('Cinematic');
 const [error,setError]=useState(''),[message,setMessage]=useState(''),[seconds,setSeconds]=useState(3),[paused,setPaused]=useState(false);
 const check=useRef<HumanCheckHandle>(null),request=useRef<AbortController|null>(null),timer=useRef<ReturnType<typeof setTimeout>|null>(null),ticker=useRef<ReturnType<typeof setInterval>|null>(null);
 const alive=useRef(false),version=useRef(0),owned=useRef(false),launcher=useRef<HTMLButtonElement>(null),panel=useRef<HTMLDivElement>(null),latest=useRef(props);
 useEffect(()=>{latest.current=props;});
 function clearTimer(){if(timer.current)clearTimeout(timer.current);if(ticker.current)clearInterval(ticker.current);timer.current=null;ticker.current=null;}
 function cancel(){version.current++;request.current?.abort();request.current=null;clearTimer();if(owned.current){latest.current.onStop();owned.current=false;}}
 useEffect(()=>{alive.current=true;setMounted(true);return()=>{alive.current=false;version.current++;request.current?.abort();clearTimer();if(owned.current)latest.current.onStop();};},[]);
 useEffect(()=>{if(open)panel.current?.querySelector<HTMLElement>('textarea, a, button')?.focus({preventScroll:true});},[open]);
 useEffect(()=>{if(open&&props.busy&&step==='countdown'){clearTimer();version.current++;setStep('style');setMessage('The studio is busy. Choose a style again when it finishes.');}},[open,props.busy,step]);
 useEffect(()=>{if(step==='countdown'&&props.currentPrompt.trim()!==draft.trim()){clearTimer();version.current++;setDraft(props.currentPrompt);setStep('review');setMessage('The studio prompt changed. Review it before choosing a style again.');}},[props.currentPrompt,step,draft]);
 function close(){cancel();if(step==='enhancing')setStep('idea');if(step==='countdown'||step==='generating'){setStep('style');setMessage('Stopped. Completed images stay in the studio. An in-flight request may still use quota.');}setOpen(false);launcher.current?.focus();}
 function scrollToStudio(){document.getElementById('studio')?.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'start'});}
 function applyOriginal(){if(idea.trim().length<3)return;cancel();setDraft(idea.trim());latest.current.onApply(idea.trim());setError('');setMessage('Using your original idea. No AI enhancement was applied.');setStep('review');scrollToStudio();}
 async function enhance(e:FormEvent){e.preventDefault();if(request.current||props.busy||!props.signedIn)return;cancel();const current=++version.current;const control=new AbortController();request.current=control;setStep('enhancing');setError('');setMessage('Shaping the subject, composition, lighting and details…');
 try{const token=await check.current?.verify(control.signal);if(!token)throw Error('Complete verification to continue.');if(control.signal.aborted)return;
 const timeout=setTimeout(()=>control.abort(),45000);let response:Response;try{response=await fetch('/api/enhance',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({idea:idea.trim(),turnstileToken:token}),signal:control.signal});}finally{clearTimeout(timeout);}
 const body=await response.json();if(!response.ok)throw Error(body.error?.message??'Prompt enhancement failed.');if(typeof body.prompt!=='string'||body.prompt.length<20||body.prompt.length>1500)throw Error('The enhanced prompt was invalid.');
 if(!alive.current||version.current!==current||control.signal.aborted)return;setDraft(body.prompt);latest.current.onApply(body.prompt);setMessage('Your improved prompt is in the studio. Edit it below if you want.');setStep('review');scrollToStudio();
 }catch(e){if(alive.current&&version.current===current){setError(control.signal.aborted?'Enhancement stopped or timed out.':e instanceof Error?e.message:'Could not enhance the prompt.');setStep('idea');}}
 finally{if(request.current===control)request.current=null;}}
 function selectStyle(next:GenerationStyle){if(timer.current||owned.current||props.busy)return;if(draft.trim().length<3||draft.length>1700){setError('Use a prompt between 3 and 1700 characters.');setStep('review');return;}const snapshot={prompt:draft.trim(),style:next,count};setStyle(next);latest.current.onApply(snapshot.prompt,{style:next,count});setSeconds(3);setStep('countdown');setError('');setMessage('');scrollToStudio();const current=++version.current;
 ticker.current=setInterval(()=>setSeconds(s=>Math.max(1,s-1)),1000);
 timer.current=setTimeout(async()=>{clearTimer();if(!alive.current||version.current!==current)return;owned.current=true;setStep('generating');setMessage('Generating in the studio. Complete the verification below if asked.');
 try{const outcome=await latest.current.onGenerate(snapshot);if(!alive.current||version.current!==current)return;setStep('done');setError(outcome.error??'');setMessage(outcome.cancelled?'Stopped. Completed images stay in the studio.':`${outcome.completed} image${outcome.completed===1?'':'s'} ready in the studio. Download your favorites there.`);}catch{if(alive.current&&version.current===current){setError('Generation could not start. Check the studio for details.');setStep('done');}}finally{if(version.current===current)owned.current=false;}
 },3000);}
 if(!mounted)return null;
 return <div className="df-fireball" data-paused={paused} data-state={step}>
 {open&&<div className="df-fireball-panel" role="dialog" aria-modal="false" aria-labelledby="fireball-title" ref={panel} onKeyDown={e=>{if(e.key==='Escape'){e.stopPropagation();close();}}}>
 <header><div className="df-fireball-avatar"><img src="/images/dreamforge/fireball-guide.png" alt=""/></div><div><strong id="fireball-title">Fireball</strong><span>Your creative guide</span></div><button type="button" aria-label="Close Fireball" onClick={close}>×</button></header>
 <div className="df-fireball-body">
 {!props.signedIn?<><h3>Let’s make your idea glow.</h3><p>Sign in first. Then describe an idea and Fireball will guide you through your first image.</p><a className="df-fireball-primary" href="#account" onClick={close}>Go to sign in</a></>:<>
 {step==='idea'&&<form onSubmit={enhance}><p className="df-fireball-step">01 / YOUR IDEA</p><h3>What shall we create?</h3><p>Start simple. “An image of an apple” is enough.</p><label htmlFor="fireball-idea">Describe your idea</label><textarea id="fireball-idea" value={idea} onChange={e=>setIdea(e.target.value)} maxLength={700} rows={3} placeholder="An image of an apple" disabled={props.busy}/><button type="submit" className="df-fireball-primary" disabled={props.busy||idea.trim().length<3}>Improve my prompt ✦</button><button type="button" className="df-fireball-link" disabled={props.busy||idea.trim().length<3} onClick={applyOriginal}>Use my original prompt</button><small>AI enhancement uses your shared Cloudflare allowance. No images start until you choose a count and style.</small></form>}
 {step==='enhancing'&&<><p className="df-fireball-step">CRAFTING YOUR PROMPT</p><h3>Adding a little spark…</h3><div className="df-fireball-thinking" aria-hidden="true">✦ <span>✦</span> ✦</div><p>{message}</p><button type="button" onClick={()=>{cancel();setStep('idea');setMessage('Enhancement stopped.');}}>Cancel enhancement</button></>}
 {step==='review'&&<><p className="df-fireball-step">02 / YOUR PROMPT</p><h3>A clearer creative direction.</h3><p>{message}</p><label htmlFor="fireball-draft">Review your prompt</label><textarea id="fireball-draft" value={draft} maxLength={1700} rows={6} disabled={props.busy} onChange={e=>{setDraft(e.target.value);latest.current.onApply(e.target.value);}}/><button type="button" className="df-fireball-primary" disabled={props.busy||draft.trim().length<3} onClick={()=>{setStep('count');setMessage('');}}>Choose image count →</button><button type="button" className="df-fireball-link" disabled={props.busy} onClick={()=>{setStep('idea');setError('');}}>Change the idea</button></>}
 {step==='count'&&<><p className="df-fireball-step">03 / HOW MANY?</p><h3>How many images?</h3><div className="df-fireball-counts">{[1,2,4].map(n=><button key={n} type="button" disabled={props.busy} onClick={()=>{setCount(n);setStep('style');setMessage('');}}><strong>{n}</strong><span>{n===1?'image':'images'}</span></button>)}</div><small>Each image is a separate request. Batches wait 31 seconds between images.</small><button type="button" className="df-fireball-link" onClick={()=>setStep('review')}>← Edit prompt</button></>}
 {step==='style'&&<><p className="df-fireball-step">04 / PICK A LOOK</p><h3>Which style feels right?</h3><p>Choose a style to start <strong>{count} {count===1?'image':'images'}</strong> automatically after a 3-second cancel window.</p><div className="df-fireball-styles">{styles.map(s=><button type="button" key={s.name} disabled={props.busy} onClick={()=>selectStyle(s.name)}><strong>{s.name}</strong><span>{s.detail}</span><b aria-hidden="true">↗</b></button>)}</div><small>Schnell · default canvas · normal daily limits apply.</small><button type="button" className="df-fireball-link" onClick={()=>setStep('count')}>← Change image count</button></>}
 {step==='countdown'&&<><p className="df-fireball-step">READY TO CREATE</p><h3>Starting in {seconds}…</h3><p>{count} {count===1?'image':'images'} · {style} · Schnell</p><button type="button" className="df-fireball-primary" onClick={()=>{cancel();setStep('style');setMessage('Automatic start cancelled.');}}>Cancel automatic start</button></>}
 {step==='generating'&&<><p className="df-fireball-step">YOUR IDEA IS TAKING SHAPE</p><h3>Creating {Math.max(1,props.progress)} of {count}…</h3><p>{message}</p><small>Verification appears in the studio behind this panel. Minimize the guide to complete it if needed; generation keeps running.</small><button type="button" onClick={()=>{cancel();setStep('done');setMessage('Stopped. Completed images stay in the studio; an in-flight request may still use quota.');}}>Stop generation</button><button type="button" className="df-fireball-link" onClick={()=>setOpen(false)}>Minimize guide</button></>}
 {step==='done'&&<><p className="df-fireball-step">YOUR STUDIO</p><h3>{error?'Let’s check what happened.':'Your next idea starts here.'}</h3><p>{message}</p><button type="button" className="df-fireball-primary" onClick={()=>{scrollToStudio();setOpen(false);}}>View the studio</button><button type="button" className="df-fireball-link" disabled={props.busy} onClick={()=>{setStep('idea');setError('');setMessage('');}}>Start another idea</button></>}
 {(step==='idea'||step==='enhancing')&&<HumanCheck ref={check} action="enhance"/>}
 </>}
 {props.busy&&step!=='generating'&&<p className="df-fireball-info">The studio is generating. New guide requests will be available when it finishes.</p>}
 {error&&<p className="df-fireball-error" role="alert">{error}</p>}
 {message&&['style','count','idea'].includes(step)&&<p role="status">{message}</p>}
 </div><footer><span>DreamForge guide</span><button type="button" onClick={()=>setPaused(p=>!p)} aria-pressed={paused}>{paused?'Play motion':'Pause motion'}</button></footer></div>}
 <button className="df-fireball-launcher" ref={launcher} type="button" aria-label={open?'Close Fireball guide':'Open Fireball guide'} aria-expanded={open} onClick={()=>open?close():setOpen(true)}><span className="df-fireball-halo"/><img src="/images/dreamforge/fireball-guide.png" alt=""/><span className="df-fireball-bubble">{step==='generating'?'Creating…':'Create with Fireball'}</span></button>
 </div>;
}
