"use client";
import {useCallback,useEffect,useRef,useState} from "react";
import {useAccount} from "./AccountProvider";
type Item={id:string;prompt:string;style:string;engine:string;canvas:string;created_at:string;mime_type:string};
export default function History(){const{user,refresh}=useAccount();const[items,setItems]=useState<Item[]>([]),[page,setPage]=useState(0),[more,setMore]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[confirm,setConfirm]=useState(''),[deleting,setDeleting]=useState('');const version=useRef(0);
 const load=useCallback(async(next:number)=>{if(!user)return;const id=++version.current;setBusy(true);setError('');try{const r=await fetch(`/api/history?page=${next}`,{cache:'no-store'});const b=await r.json();if(!r.ok){if(r.status===401)void refresh();throw Error(b.error?.message??'History unavailable.');}if(id===version.current){setItems(b.items);setMore(b.hasMore);setPage(next);}}catch(e){if(id===version.current)setError(e instanceof Error?e.message:'History unavailable.');}finally{if(id===version.current)setBusy(false);}},[user,refresh]);
 useEffect(()=>{setItems([]);setPage(0);setMore(false);setConfirm('');setError('');if(user)void load(0);const update=()=>void load(0);window.addEventListener('dreamforge-history',update);return()=>{version.current++;window.removeEventListener('dreamforge-history',update);};},[user?.id,load]);
 async function remove(id:string){setDeleting(id);setError('');try{const r=await fetch(`/api/history/${id}`,{method:'DELETE'});if(!r.ok){const b=await r.json();throw Error(b.error?.message??'Could not delete image.');}setConfirm('');await load(items.length===1&&page>0?page-1:page);}catch(e){setError(e instanceof Error?e.message:'Delete failed.');}finally{setDeleting('');}}
 return <section id="history" className="df-section df-history" aria-labelledby="history-title"><p className="df-eyebrow">SAVED FOR YOU</p><div className="df-section-heading"><h2 id="history-title">Your private gallery.</h2>{user&&<button disabled={busy} onClick={()=>void load(0)}>Refresh gallery</button>}</div>{!user?<p><a href="#account">Sign in</a> to view your saved images.</p>:<>{error&&<p role="alert" className="df-error">{error}</p>}{busy&&<p role="status">Loading your history…</p>}{!busy&&!error&&items.length===0&&<p>No saved images yet. Your next successful generation will appear here.</p>}<div className="df-history-grid">{items.map(item=><article key={item.id}><img loading="lazy" src={`/api/history/${item.id}`} alt={item.prompt}/><div><p>{item.prompt}</p><small>{item.engine} · {item.style} · {new Date(item.created_at).toLocaleDateString()}</small><div className="df-history-actions"><a href={`/api/history/${item.id}?download=1`} download>Download ↓</a><button disabled={!!deleting} onClick={()=>setConfirm(item.id)}>Delete</button></div>{confirm===item.id&&<div className="df-delete-confirm"><p>Delete this saved image permanently?</p><button disabled={!!deleting} onClick={()=>void remove(item.id)}>{deleting===item.id?'Deleting…':'Yes, delete'}</button><button disabled={!!deleting} onClick={()=>setConfirm('')}>Cancel</button></div>}</div></article>)}</div><div className="df-history-pages"><button disabled={busy||page===0} onClick={()=>void load(page-1)}>Previous</button><span>Page {page+1}</span><button disabled={busy||!more} onClick={()=>void load(page+1)}>Next</button></div></>}</section>;
}
