"use client";
import {useEffect,useRef,useState} from "react";
import {useAccount} from "./AccountProvider";
import {composePrompt,exportBoard,MAX_CHARACTERS,MAX_SCENES,parseBoard,starterBoard,storyboardHtml,type Board,type Character,type Scene} from "../../lib/storyboard";
import "./story-lab.css";

function download(content:string,type:string,name:string){const url=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
async function readImage(file:File):Promise<string>{
 if(!['image/png','image/jpeg'].includes(file.type)||file.size>3*1024*1024)throw Error('Choose a PNG or JPEG under 3 MiB.');
 const bitmap=await createImageBitmap(file);const area=bitmap.width*bitmap.height;bitmap.close();if(area>16000000)throw Error('Choose an image below 16 megapixels.');
 return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=()=>reject(Error('Could not read this image.'));reader.readAsDataURL(file);});
}
export default function StoryLab({onUse}:{onUse:(prompt:string)=>void}){
 const {user,loading}=useAccount();
 return <section id="lab" className="df-lab df-section" aria-labelledby="lab-title"><p className="df-eyebrow">PHASE 7 / CHARACTER & STORY LAB</p><h2 id="lab-title">One character. Many scenes.</h2><p className="df-lab-lead">Build a character profile, plan up to six scenes, then create each image in the studio.</p><p className="df-lab-disclosure">Profiles repeat text descriptions; they do not lock faces. Reference photos stay on this page and are not sent to Cloudflare. LoRA training runs separately in the included notebook.</p>{loading?<p>Checking your account…</p>:user?<Editor key={user.id} userId={user.id} onUse={onUse}/>:<p><a href="#account">Sign in</a> to open your storyboard workspace.</p>}</section>;
}
function Editor({userId,onUse}:{userId:string;onUse:(prompt:string)=>void}){
 const [board,setBoard]=useState<Board>(starterBoard),[ready,setReady]=useState(false),[message,setMessage]=useState(''),[dirty,setDirty]=useState(false);
 const [frames,setFrames]=useState<Record<string,string>>({}),[reference,setReference]=useState('');
 const alive=useRef(true);const imageVersions=useRef<Record<string,number>>({});const key=`dreamforge-storyboard-v1:${userId}`;
 useEffect(()=>{alive.current=true;try{const raw=localStorage.getItem(key);if(raw)setBoard(parseBoard(JSON.parse(raw)));}catch{setMessage('The saved project could not be loaded. Your stored copy was not changed.');}setReady(true);return()=>{alive.current=false;};},[key]);
 useEffect(()=>{if(!dirty)return;const warn=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue='';};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[dirty]);
 const character=board.characters.find(c=>c.id===board.characterId)!;
 function update(next:Board){setBoard(next);setDirty(true);setMessage('Unsaved text changes. Save or export your project.');}
 function changeCharacter(values:Partial<Character>){update({...board,characters:board.characters.map(c=>c.id===character.id?{...c,...values}:c)});}
 function changeScene(id:string,values:Partial<Scene>){update({...board,scenes:board.scenes.map(s=>s.id===id?{...s,...values}:s)});}
 function save(){try{localStorage.setItem(key,JSON.stringify(parseBoard(board)));setDirty(false);setMessage('Text saved for this account in this browser. Attached images are session-only.');}catch(e){setMessage(e instanceof Error?e.message:'Could not save. Check character names or export JSON.');}}
 async function importProject(file?:File){if(!file)return;try{if(file.size>100000)throw Error('JSON must be under 100 KB.');const next=parseBoard(JSON.parse(await file.text()));if(!alive.current)return;if(!confirm('Replace the open storyboard? Export or save your current text first.'))return;Object.keys(imageVersions.current).forEach(id=>{imageVersions.current[id]++;});setFrames({});setReference('');update(next);}catch(e){if(alive.current)setMessage(e instanceof Error?e.message:'Import failed.');}}
 async function attach(file:File|undefined,id:string){if(!file)return;const version=(imageVersions.current[id]??0)+1;imageVersions.current[id]=version;try{const image=await readImage(file);if(!alive.current||imageVersions.current[id]!==version)return;if(id==='reference')setReference(image);else setFrames(f=>({...f,[id]:image}));setMessage('Image attached for this session. Export HTML to keep scene artwork; reference photos are not exported.');}catch(e){if(alive.current)setMessage(e instanceof Error?e.message:'Attachment failed.');}}
 function removeImage(id:string){imageVersions.current[id]=(imageVersions.current[id]??0)+1;if(id==='reference')setReference('');else setFrames(f=>{const next={...f};delete next[id];return next;});}
 if(!ready)return <p>Loading storyboard…</p>;
 return <><div className="df-lab-toolbar"><label>Project title<input maxLength={80} value={board.title} onChange={e=>update({...board,title:e.target.value})}/></label><button type="button" onClick={save}>Save project</button><button type="button" onClick={()=>download(JSON.stringify(exportBoard(board),null,2),'application/json','dreamforge-storyboard.json')}>Export JSON</button><button type="button" onClick={()=>download(storyboardHtml(board,frames),'text/html','dreamforge-storyboard.html')}>Export HTML</button><label className="df-lab-upload">Import JSON<input type="file" accept="application/json,.json" onChange={e=>{void importProject(e.target.files?.[0]);e.target.value='';}}/></label></div>
 <p className="df-lab-status" role="status">{message||'Text saves only when you select Save project. JSON includes text only. HTML includes attached scene images.'}</p>
 <div className="df-lab-workspace"><aside className="df-lab-profile"><h3>Character profile</h3><label>Selected character<select aria-label="Selected character" value={character.id} onChange={e=>{setReference('');imageVersions.current.reference=(imageVersions.current.reference??0)+1;update({...board,characterId:e.target.value});}}>{board.characters.map(c=><option key={c.id} value={c.id}>{c.name||'Unnamed character'}</option>)}</select></label><label>Character name<input value={character.name} maxLength={40} onChange={e=>changeCharacter({name:e.target.value})}/></label><label>Stable description<textarea aria-label="Stable description" value={character.description} maxLength={500} rows={5} onChange={e=>changeCharacter({description:e.target.value})}/></label><label>Clothing / accessories<input value={character.wardrobe} maxLength={160} onChange={e=>changeCharacter({wardrobe:e.target.value})}/></label><div className="df-lab-actions"><button disabled={board.characters.length>=MAX_CHARACTERS} onClick={()=>{const id=crypto.randomUUID();setReference('');imageVersions.current.reference=(imageVersions.current.reference??0)+1;update({...board,characterId:id,characters:[...board.characters,{id,name:'New character',description:'',wardrobe:''}]});}}>Add character</button><button disabled={board.characters.length===1} onClick={()=>{if(!confirm('Delete this character profile?'))return;const characters=board.characters.filter(c=>c.id!==character.id);removeImage('reference');update({...board,characters,characterId:characters[0].id});}}>Delete character</button></div><label>Reference photo (view only)<input type="file" accept="image/png,image/jpeg" onChange={e=>{void attach(e.target.files?.[0],'reference');e.target.value='';}}/></label>{reference&&<><img className="df-lab-reference" src={reference} alt="Your reference, for visual comparison only"/><button onClick={()=>removeImage('reference')}>Remove reference</button></>}<small>The reference is temporary and not used by the image model. Only use images you have permission to use.</small><label>Shared visual direction<textarea aria-label="Shared visual direction" rows={3} maxLength={200} value={board.direction} onChange={e=>update({...board,direction:e.target.value})}/></label><button onClick={()=>{if(!confirm('Delete the saved storyboard text for this account in this browser and reset the open project?'))return;try{localStorage.removeItem(key);Object.keys(imageVersions.current).forEach(id=>{imageVersions.current[id]++;});setBoard(starterBoard());setFrames({});setReference('');setDirty(false);setMessage('Saved text deleted. A fresh example is open.');}catch{setMessage('Could not delete browser data. Check browser storage permissions.');}}}>Clear saved project</button></aside>
 <div className="df-lab-scenes"><div className="df-lab-scenes-heading"><h3>Storyboard <span>{board.scenes.length}/{MAX_SCENES}</span></h3><button disabled={board.scenes.length>=MAX_SCENES} onClick={()=>update({...board,scenes:[...board.scenes,{id:crypto.randomUUID(),title:`Scene ${board.scenes.length+1}`,action:'',setting:'',shot:'Wide shot'}]})}>Add scene</button></div>
 {board.scenes.map((scene,index)=>{const prompt=composePrompt(board,scene);const usable=!!character.name.trim()&&character.description.trim().length>=3&&!!scene.action.trim()&&prompt.length<=1700;return <article key={scene.id} className="df-lab-scene"><div className="df-lab-scene-heading"><strong>SCENE {String(index+1).padStart(2,'0')}</strong><div className="df-lab-actions"><button aria-label={`Move scene ${index+1} up`} disabled={index===0} onClick={()=>{const scenes=[...board.scenes];[scenes[index-1],scenes[index]]=[scenes[index],scenes[index-1]];update({...board,scenes});}}>↑</button><button aria-label={`Remove scene ${index+1}`} disabled={board.scenes.length===1} onClick={()=>{removeImage(scene.id);update({...board,scenes:board.scenes.filter(s=>s.id!==scene.id)});}}>Remove</button></div></div><label>Scene title<input maxLength={60} value={scene.title} onChange={e=>changeScene(scene.id,{title:e.target.value})}/></label><div className="df-lab-scene-fields"><label>Action<textarea aria-label="Action" maxLength={350} rows={3} value={scene.action} onChange={e=>changeScene(scene.id,{action:e.target.value})}/></label><label>Location / time<textarea aria-label="Location / time" maxLength={250} rows={3} value={scene.setting} onChange={e=>changeScene(scene.id,{setting:e.target.value})}/></label></div><label>Camera framing<select aria-label="Camera framing" value={scene.shot} onChange={e=>changeScene(scene.id,{shot:e.target.value})}>{Array.from(new Set([scene.shot,'Wide shot','Medium shot','Close-up','Over-the-shoulder shot','Low-angle shot','Top-down shot'])).map(s=><option key={s}>{s}</option>)}</select></label><details><summary>Composed prompt · {prompt.length}/1700</summary><p className="df-lab-prompt">{prompt}</p></details><div className="df-lab-actions"><button className="df-lab-primary" disabled={!usable} onClick={()=>{onUse(prompt);setMessage(`Scene ${index+1} sent to studio. Review the model and settings, then generate. Each image uses the normal quota.`);}}>Use in studio</button><button disabled={!usable} onClick={async()=>{try{await navigator.clipboard.writeText(prompt);setMessage('Prompt copied.');}catch{setMessage('Clipboard unavailable. Expand Composed prompt and copy its text.');}}}>Copy prompt</button></div>{!usable&&<p>Add a character name, description and scene action; keep the prompt under 1700 characters.</p>}<label>Attach downloaded result<input type="file" accept="image/png,image/jpeg" onChange={e=>{void attach(e.target.files?.[0],scene.id);e.target.value='';}}/></label>{frames[scene.id]&&<><img className="df-lab-frame" src={frames[scene.id]} alt={`Manually attached artwork for ${scene.title}`}/><small>Manually attached artwork • compare against the current prompt after edits.</small><button onClick={()=>removeImage(scene.id)}>Remove artwork</button></>}</article>;})}
 </div></div><details className="df-lab-research"><summary>LoRA experiment: what happens next?</summary><p>Open research/DreamForge-LoRA-Colab.ipynb from your Phase 7 ZIP in Colab. Train a small adapter using your own character or style images, then compare the base model and trained model with the same seed. You can also upload this storyboard’s JSON to render its scenes there.</p><p>A GPU is required. GPU availability and training results are not guaranteed. The adapter is for the notebook’s Stable Diffusion model and cannot be loaded into this app’s existing Schnell/Phoenix routes. Download your notebook results and attach them to scene cards for HTML export.</p></details></>;
}
